apiVersion: v1
kind: Service
metadata:
  name: node-web-service
  labels:
    app: node-web-app
    run: node-web-app
   annotations:
    version: "1.0"
    description: "Service exposant l'application Node.js sur le port 80"
    contact: "admin@yourdomain.com"
spec:
  selector:
    app: node-web-app
    run: node-web-app
  ports:
  - protocol: TCP
    port: 80              # Le port sur lequel le service écoute
    targetPort: 3000      # Le port sur lequel votre conteneur écoute
    nodePort: 30946       # (Optionnel) Spécifiez le NodePort si nécessaire
  type: NodePort          # Ou ClusterIP si vous utilisez Ingress
  #externalIPs:
  #  - 192.168.49.2


